name: aws-c-cal

permissions:
  contents: write
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/aws-c-cal.yml"
      - "ports/aws-c-cal/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/aws-c-cal.yml"
      - "ports/aws-c-cal/**"

jobs:
  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'aws-c-cal')))
    steps:
      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          path: build-files

      - name: Checkout aws-c-common
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/aws-c-common
          path: aws-c-common

      - name: Checkout aws-c-cal
        uses: actions/checkout@v4
        with:
          repository: awslabs/aws-c-cal
          path: aws-c-cal
          ref: v0.9.10

      - name: Build aws-c-cal
        shell: bash
        run: |
          if [[ ${{ matrix.qnx_env }} == 710 ]]; then
            source ~/qnx/710/qnxsdp-env.sh
          else
            source ~/qnx/800/qnxsdp-env.sh
          fi
          make -C build-files/ports/aws-c-common install
          make -C build-files/ports/aws-c-cal install
