name: check

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/check.yml'
      - 'ports/check/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/check.yml'
      - 'ports/check/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'check')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/build-files
        path: build-files

    - name: Checkout check
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/check
        path: check
        submodules: 'true'

    - name: Build check
      shell: bash
      run: |
        source ~/qnx/800/qnxsdp-env.sh
        BUILD_TESTING="ON" QNX_PROJECT_ROOT="$(pwd)/check" make -C build-files/ports/check install

