name: conan-lighttpd1.4

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/conan-lighttpd1.4.yml'
      - 'conan/recipes/lighttpd1.4/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/conan-lighttpd1.4.yml'
      - 'conan/recipes/lighttpd1.4/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'conan')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Build conan lightttpd1.4 recipes
      shell: bash
      run: |
        python3.11 -m venv vpy
        . vpy/bin/activate
        pip install conan
        conan profile detect
        export QNX_CONAN_ROOT=$(realpath ./build-files/conan)
        conan config install $QNX_CONAN_ROOT/tools/qnx-8.0-extension/settings_user.yml
        source ~/qnx/800/qnxsdp-env.sh
        conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-8.0-x86_64-gcc --version=1.4.73 $QNX_CONAN_ROOT/recipes/lighttpd1.4/all --build=missing
        conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-8.0-x86_64-gcc --version=1.4.81 $QNX_CONAN_ROOT/recipes/lighttpd1.4/all --build=missing
