name: gtk

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/gtk.yml'
      - 'ports/gtk/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/gtk.yml'
      - 'ports/gtk/**'

jobs:
  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'gtk'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout gtk
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/gtk
        path: gtk

    - name: Checkout meson
      uses: actions/checkout@v4
      with:
        repository: mesonbuild/meson
        path: meson
        ref: 1.3.1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp800-build-env:latest

    - name: Build gtk
      uses: addnab/docker-run-action@v3
      with:
        image: qnx800:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          source ~/qnx800/qnxsdp-env.sh
          export QCONF_OVERRIDE=/home/runner/build-files/resources/qconf_override/qconf_override.mk
          QNX_PROJECT_ROOT="$(pwd)/gtk" make -C build-files/ports/gtk install -j$(nproc)
