name: mpfr

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/mpfr.yml'
      - 'ports/mpfr/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/mpfr.yml'
      - 'ports/mpfr/**'

jobs:

  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build MPFR for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'mpfr')))
    steps:
      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          path: build-files

      - name: Download and extract MPFR
        run: |
          cd ${{ github.workspace }}
          curl -L -o mpfr-4.2.2.tar.xz https://www.mpfr.org/mpfr-4.2.2/mpfr-4.2.2.tar.xz
          tar -xvf mpfr-4.2.2.tar.xz
          mv mpfr-4.2.2 mpfr
          
      - name: Set up QNX environment and build
        shell: bash
        run: |
          if [[ "${{ matrix.qnx_env }}" == "800" ]]; then
            source ~/qnx/800/qnxsdp-env.sh
          else
            source ~/qnx/710/qnxsdp-env.sh
          fi
          QNX_PROJECT_ROOT="$(pwd)/mpfr" make -C build-files/ports/mpfr install
