name: rapidjson

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/rapidjson.yml'
      - 'ports/rapidjson/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/rapidjson.yml'
      - 'ports/rapidjson/**'

jobs:

  build_master:
    strategy:
      matrix:
        qnx_env: [710, 800]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'rapidjson'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout rapidjson
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/rapidjson
        path: rapidjson
        ref: qnx-master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp-build-env:latest

    - name: Build rapidjson
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          if [ "${{ matrix.qnx_env }}" == "710" ]; then
            source ~/qnx/710/qnxsdp-env.sh
          else
            source ~/qnx/800/qnxsdp-env.sh
          fi
          cd ~/workspace
          OSLIST="nto" QNX_PROJECT_ROOT="$(pwd)/rapidjson" make -C build-files/ports/rapidjson install 

  build_v110:
    strategy:
      matrix:
        qnx_env: [710, 800]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'rapidjson'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout rapidjson
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/rapidjson
        path: rapidjson
        ref: qnx-v1.1.0


    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp-build-env:latest

    - name: Build rapidjson
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          if [ "${{ matrix.qnx_env }}" == "710" ]; then
            source ~/qnx/710/qnxsdp-env.sh
          else
            source ~/qnx/800/qnxsdp-env.sh
          fi
          cd ~/workspace
          OSLIST="nto" QNX_PROJECT_ROOT="$(pwd)/rapidjson" make -C build-files/ports/rapidjson install 