name: sysbench

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sysbench.yml'
      - 'ports/sysbench/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/sysbench.yml'
      - 'ports/sysbench/**'
jobs:

  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build sysbench for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'sysbench')))
    steps:
      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          path: build-files
          
      - name: Checkout sysbench repo (branch qnx-1.0.20)
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/sysbench
          ref: qnx-1.0.20
          path: sysbench
    
          
      - name: Set up QNX environment and build
        shell: bash
        run: |
          if [[ "${{ matrix.qnx_env }}" == "800" ]]; then
            source ~/qnx/800/qnxsdp-env.sh
          else
            source ~/qnx/710/qnxsdp-env.sh
          fi
          QNX_PROJECT_ROOT="$(pwd)/sysbench" make -C build-files/ports/sysbench install
