name: unbound

permissions:
  contents: write
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/unbound.yml'
      - 'ports/unbound/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/unbound.yml'
      - 'ports/unbound/**'

jobs:
  build:
    strategy:
      matrix:
        qnx_env: [ 710, 800 ]
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'unbound')))
    steps:
      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          path: build-files

      - name: Checkout Unbound
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/unbound
          path: unbound
          ref: qnx-release-1.24.1

      - name: Build unbound
        shell: bash
        run: |
          if [[ "${{ matrix.qnx_env }}" == "800" ]]; then
            source ~/qnx/800/qnxsdp-env.sh
          else
            source ~/qnx/710/qnxsdp-env.sh
          fi
          JLEVEL=$(nproc) QNX_PROJECT_ROOT="$(pwd)/unbound" make -C build-files/ports/unbound/ install
